name: Squash repository history

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  squash_master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          
      - name: Setup git
        run: |
          git config user.name "cleanup-workflow"
          git config user.email "actions@github.com"

      - name: Run squash script
        run: |
          git branch master_backup master

          git checkout --orphan master_squashed

          git add -A
          git commit -m "Initial commit of the project with squashed history"

          git branch -D master
          git branch -m master
          
      - name: Force push squashed history
        run: git push origin master --force